package com.rajyouradmirerorg.gitdemo3;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CardData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public CardData() {

		System.out.println();
	}

}